#Import the Standard library and Load The Dataset

In [10]:
#import the Standard library
import pandas as pd
import numpy as np

In [11]:
# load the dataset
df = pd.read_csv('customer_signups.csv')

#Explore the Dataset

In [12]:
df.head(5)

,customer_id,name,email,signup_date,source,region,plan_selected,marketing_opt_in,age,gender
0,CUST00000,Joshua Bryant,NaN,NaN,Instagram,NaN,basic,No,34,Female
1,CUST00001,Nicole Stewart,nicole1@example.com,02-01-24,LinkedIn,West,basic,Yes,29,Male
2,CUST00002,Rachel Allen,rachel2@example.com,03-01-24,Google,North,PREMIUM,Yes,34,Non-Binary
3,CUST00003,Zachary Sanchez,zachary3@mailhub.org,04-01-24,YouTube,NaN,Pro,No,40,Male
4,CUST00004,NaN,matthew4@mailhub.org,05-01-24,LinkedIn,West,Premium,No,25,Other

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 289 entries, 0 to 299
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       289 non-null    object
 1   name              289 non-null    object
 2   email             257 non-null    object
 3   signup_date       284 non-null    datetime64[ns]
 4   source            289 non-null    object
 5   region            289 non-null    object
 6   plan_selected     289 non-null    object
 7   marketing_opt_in  289 non-null    object
 8   age               270 non-null    float64
 9   gender            289 non-null    object
 10  signup_week       284 non-null    datetime64[ns]
 11  age_group         269 non-null    category
dtypes: category(1), datetime64[ns](2), float64(1), object(8)
memory usage: 27.6+ KB

In [14]:
df.describe(include='all')

,customer_id,name,email,signup_date,source,region,plan_selected,marketing_opt_in,age,gender
count,298,291,266,298,291,270,292,290,288,292
unique,298,291,265,295,7,5,8,3,11,7
top,CUST00299,Mr. Bruce Bridges,lisa11@mailhub.org,not a date,YouTube,North,Premium,No,40,Other
freq,1,1,2,4,58,65,57,156,50,59

In [52]:
df.dtypes

customer_id                 object
name                        object
email                       object
signup_date         datetime64[ns]
source                      object
region                      object
plan_selected               object
marketing_opt_in            object
age                        float64
gender                      object
signup_week         datetime64[ns]
age_group                 category
dtype: object

#Clean The Dataset

In [51]:
df.signup_date = pd.to_datetime(df.signup_date, errors='coerce')

In [17]:
df.plan_selected = df.plan_selected.str.strip().str.title()
df.marketing_opt_in = df.marketing_opt_in.str.strip().str.title()
df.source = df.source.str.strip().str.title()
df.region = df.region.str.strip().str.title()
df.gender = df.gender.str.strip().str.title()

In [49]:
df.head(10)

,customer_id,name,email,signup_date,source,region,plan_selected,marketing_opt_in,age,gender,signup_week,age_group
0,CUST00000,Joshua Bryant,NaN,NaT,Instagram,Unknown,Basic,No,34.0,Female,NaT,"(25, 35]"
1,CUST00001,Nicole Stewart,nicole1@example.com,2024-02-01,Linkedin,West,Basic,Yes,29.0,Male,2024-01-29,"(25, 35]"
2,CUST00002,Rachel Allen,rachel2@example.com,2024-03-01,Google,North,Premium,Yes,34.0,Non-Binary,2024-02-26,"(25, 35]"
3,CUST00003,Zachary Sanchez,zachary3@mailhub.org,2024-04-01,Youtube,Unknown,Pro,No,40.0,Male,2024-04-01,"(35, 50]"
5,CUST00005,John Gonzales,john5@mailhub.org,2024-06-01,Facebook,South,Premium,No,34.0,Other,2024-05-27,"(25, 35]"
6,CUST00006,Crystal Mason,crystal6@mailhub.org,2024-07-01,Youtube,North,Unknownplan,Yes,40.0,Male,2024-07-01,"(35, 50]"
7,CUST00007,Michael Bailey,michael7@mailhub.org,2024-08-01,Youtube,Central,Pro,Yes,60.0,Other,2024-07-29,"(50, 70]"
8,CUST00008,Bianca Morris,bianca8@example.com,2024-09-01,Referral,West,Pro,Yes,25.0,Male,2024-08-26,"(18, 25]"
9,CUST00009,Cindy Anderson,NaN,2024-10-01,Google,East,Premium,No,29.0,Female,2024-09-30,"(25, 35]"
10,CUST00010,Kendra Gill,kendra10@mailhub.org,2024-11-01,Google,Central,Pro,No,29.0,Male,2024-10-28,"(25, 35]"

In [48]:
df.duplicated('customer_id').sum()

np.int64(0)

In [20]:
df.isnull().sum()

customer_id          2
name                 9
email               34
signup_date          6
source               9
region              30
plan_selected        8
marketing_opt_in    10
age                 12
gender               8
dtype: int64

In [21]:
#replace rows with missing region value
df["region"] = df["region"].fillna("Unknown")

In [22]:
#remove rows with missing column id value
df = df[df["customer_id"].notna()]

In [23]:
#replace rows with missing plan selected value
df.loc[:,"plan_selected"] = df["plan_selected"].fillna("Not Selected")

In [24]:
#remove rows with missing name value
df = df[df['name'].notna()]

In [25]:
#marketing_opt_in with missing value since the value is "Yes" or "No" if they didn't select it, it should be No
df["marketing_opt_in"] = df["marketing_opt_in"].fillna("No")

In [26]:
# age convert invalid ages to missing
df["age"] = pd.to_numeric(df["age"], errors="coerce")

In [27]:
# age convert invalid ages to missing
df["gender"] = df["gender"].fillna("Unknown")

In [28]:
df.isnull().sum()

customer_id          0
name                 0
email               32
signup_date          5
source               9
region               0
plan_selected        0
marketing_opt_in     0
age                 19
gender               0
dtype: int64

In [29]:
df.describe()

                         signup_date         age
count                            284  270.000000
mean   2024-06-10 10:28:43.943662080   36.292593
min              2024-01-02 00:00:00   21.000000
25%              2024-03-18 18:00:00   25.000000
50%              2024-06-09 12:00:00   34.000000
75%              2024-08-29 06:00:00   40.000000
max              2024-12-10 00:00:00  206.000000
std                              NaN   15.223720

#Summary Output using Pandas Aggregations

In [30]:
print(df.columns.tolist())

['customer_id', 'name', 'email', 'signup_date', 'source', 'region', 'plan_selected', 'marketing_opt_in', 'age', 'gender']

In [54]:
df['signup_week'] = df['signup_date'].dt.to_period('W').dt.start_time
df.groupby('signup_week').size()

signup_week
2024-01-01    6
2024-01-08    5
2024-01-15    7
2024-01-22    7
2024-01-29    7
2024-02-05    6
2024-02-12    6
2024-02-19    7
2024-02-26    7
2024-03-04    7
2024-03-11    5
2024-03-18    6
2024-03-25    6
2024-04-01    7
2024-04-08    4
2024-04-15    7
2024-04-22    7
2024-04-29    5
2024-05-06    4
2024-05-13    6
2024-05-20    7
2024-05-27    6
2024-06-03    7
2024-06-10    4
2024-06-17    7
2024-06-24    7
2024-07-01    7
2024-07-08    5
2024-07-15    6
2024-07-22    7
2024-07-29    7
2024-08-05    5
2024-08-12    5
2024-08-19    7
2024-08-26    6
2024-09-02    7
2024-09-09    5
2024-09-16    7
2024-09-23    7
2024-09-30    6
2024-10-07    5
2024-10-14    6
2024-10-21    6
2024-10-28    3
2024-11-04    7
2024-11-25    1
2024-12-02    7
2024-12-09    2
dtype: int64

In [32]:
df['source'] = df['source'].fillna('Unknown')

In [33]:
df['source'].value_counts()

source
Youtube      55
Referral     48
Google       47
Instagram    47
Facebook     40
Linkedin     37
Unknown       9
??            6
Name: count, dtype: int64

In [34]:
df['region'].value_counts()

region
North      62
East       59
South      57
West       42
Central    39
Unknown    30
Name: count, dtype: int64

In [35]:
df.isnull().sum()

customer_id          0
name                 0
email               32
signup_date          5
source               0
region               0
plan_selected        0
marketing_opt_in     0
age                 19
gender               0
signup_week          5
dtype: int64

In [36]:
df['plan_selected'].value_counts()

plan_selected
Premium         94
Pro             92
Basic           90
Not Selected     8
Unknownplan      5
Name: count, dtype: int64

In [37]:
df.groupby('gender')['marketing_opt_in'].value_counts()

gender      marketing_opt_in
123         No                   3
            Yes                  3
Female      No                  47
            Yes                 44
Male        No                  53
            Yes                 34
            Nil                  1
Non-Binary  No                  22
            Yes                 18
Other       No                  32
            Yes                 24
Unknown     No                   4
            Yes                  4
Name: count, dtype: int64

In [38]:
df['age'].describe()

count    270.000000
mean      36.292593
std       15.223720
min       21.000000
25%       25.000000
50%       34.000000
75%       40.000000
max      206.000000
Name: age, dtype: float64

#Answering the Business Questions

In [39]:
df_last_month = df[df['signup_date'].dt.month == df['signup_date'].dt.month.max()]
df_last_month['source'].value_counts()

source
Instagram    4
Youtube      2
Referral     2
Facebook     1
Linkedin     1
Name: count, dtype: int64

In [40]:
df['region'].value_counts()

region
North      62
East       59
South      57
West       42
Central    39
Unknown    30
Name: count, dtype: int64

In [41]:
df['age_group'] = pd.cut(df['age'], bins=[18,25,35,50,70,100])
df.groupby('age_group')['marketing_opt_in'].value_counts()

C:\Users\Public\Documents\iSkysoft\CreatorTemp\ipykernel_9568\2963042709.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('age_group')['marketing_opt_in'].value_counts()

age_group  marketing_opt_in
(18, 25]   No                  44
           Yes                 29
           Nil                  1
(25, 35]   No                  50
           Yes                 35
           Nil                  0
(35, 50]   Yes                 35
           No                  34
           Nil                  0
(50, 70]   No                  23
           Yes                 18
           Nil                  0
(70, 100]  Nil                  0
           No                   0
           Yes                  0
Name: count, dtype: int64

In [42]:
df.groupby(["plan_selected", "age_group"]).size()

C:\Users\Public\Documents\iSkysoft\CreatorTemp\ipykernel_9568\4215610563.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["plan_selected", "age_group"]).size()

plan_selected  age_group
Basic          (18, 25]     27
               (25, 35]     23
               (35, 50]     15
               (50, 70]     14
               (70, 100]     0
Not Selected   (18, 25]      2
               (25, 35]      3
               (35, 50]      2
               (50, 70]      1
               (70, 100]     0
Premium        (18, 25]     21
               (25, 35]     29
               (35, 50]     30
               (50, 70]     10
               (70, 100]     0
Pro            (18, 25]     24
               (25, 35]     29
               (35, 50]     19
               (50, 70]     15
               (70, 100]     0
Unknownplan    (18, 25]      0
               (25, 35]      1
               (35, 50]      3
               (50, 70]      1
               (70, 100]     0
dtype: int64

#Load the second dataset support_tickets

In [43]:
df_support = pd.read_csv('support_tickets.csv')
df_support.head(5)

   ticket_id customer_id ticket_date       issue_type resolved
0  TKT0000-1   CUST00203  2024-08-17          Billing      Yes
1  TKT0000-2   CUST00203  2024-07-22  Technical Error      Yes
2  TKT0000-3   CUST00203  2024-07-22            Other      Yes
3  TKT0001-1   CUST00266  2024-09-26    Account Setup      Yes
4  TKT0001-2   CUST00266  2024-10-09  Technical Error       No

In [44]:
merged = df.merge(df_support, on='customer_id', how='left')
merged.head(5)

,customer_id,name,email,signup_date,source,region,plan_selected,marketing_opt_in,age,gender,signup_week,age_group,ticket_id,ticket_date,issue_type,resolved
0,CUST00000,Joshua Bryant,NaN,NaT,Instagram,Unknown,Basic,No,34.0,Female,NaT,"(25, 35]",NaN,NaN,NaN,NaN
1,CUST00001,Nicole Stewart,nicole1@example.com,2024-02-01,Linkedin,West,Basic,Yes,29.0,Male,2024-01-29,"(25, 35]",NaN,NaN,NaN,NaN
2,CUST00002,Rachel Allen,rachel2@example.com,2024-03-01,Google,North,Premium,Yes,34.0,Non-Binary,2024-02-26,"(25, 35]",NaN,NaN,NaN,NaN
3,CUST00003,Zachary Sanchez,zachary3@mailhub.org,2024-04-01,Youtube,Unknown,Pro,No,40.0,Male,2024-04-01,"(35, 50]",NaN,NaN,NaN,NaN
4,CUST00005,John Gonzales,john5@mailhub.org,2024-06-01,Facebook,South,Premium,No,34.0,Other,2024-05-27,"(25, 35]",TKT0008-1,2024-06-04,Other,Yes

In [45]:
merged.groupby('plan_selected')['ticket_id'].count()

plan_selected
Basic           38
Not Selected     4
Premium         26
Pro             47
Unknownplan      4
Name: ticket_id, dtype: int64

In [46]:
merged.groupby('region')['ticket_id'].count()

region
Central    18
East       27
North      26
South      16
Unknown     5
West       27
Name: ticket_id, dtype: int64

In [47]:
df['signup_week'].describe()

count                              284
mean     2024-06-07 10:28:43.943662080
min                2024-01-01 00:00:00
25%                2024-03-18 00:00:00
50%                2024-06-06 12:00:00
75%                2024-08-26 00:00:00
max                2024-12-09 00:00:00
Name: signup_week, dtype: object